<?xml version="1.0" encoding="utf-8"?><Database Name="ReportesPurasol" Class="DatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QLPT5CO\EQUIPO_PRINCIPAL;Initial Catalog=ReportesPurasol;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="ReportesPurasolConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.ActualizarClave" Method="ActualizarClave">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarUsuario" Method="ActualizarUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ConsultaListaUsuario" Method="ConsultaListaUsuario">
    <ElementType Name="ConsultaListaUsuarioResult">
      <Column Name="usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultarUsuario" Method="ConsultarUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="ConsultarUsuarioResult">
      <Column Name="usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.EliminarCliente" Method="EliminarCliente">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarUsuario" Method="EliminarUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExisteUsuario" Method="ExisteUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="ExisteUsuarioResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ListaRoles" Method="ListaRoles">
    <ElementType Name="ListaRolesResult">
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Cantones" Method="Cantones">
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Char" DbType="Char(1)" />
    <ElementType Name="CantonesResult">
      <Column Name="Provincia" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Canton" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Distritos" Method="Distritos">
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Canton" Parameter="canton" Type="System.String" DbType="Char(2)" />
    <ElementType Name="DistritosResult">
      <Column Name="Provincia" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Canton" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Distrito" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Provincias" Method="Provincias">
    <ElementType Name="ProvinciasResult">
      <Column Name="Cod" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ObtenerRol" Method="ObtenerRol">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="ObtenerRolResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CrearActualizarCliente" Method="CrearActualizarCliente">
    <Parameter Name="cedula" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.Int32" DbType="Int" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Distrito" Parameter="distrito" Type="System.Int32" DbType="Int" />
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Int32" DbType="Int" />
    <Parameter Name="Canton" Parameter="canton" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ListaClientes" Method="ListaClientes">
    <ElementType Name="ListaClientesResult">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Distrito" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Canton" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SeleccionarCliente" Method="SeleccionarCliente">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.Int32" DbType="Int" />
    <ElementType Name="SeleccionarClienteResult">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Distrito" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Canton" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CrearUsuario" Method="CrearUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="activo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="rol" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="CrearUsuarioResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AgregarUsuario" Method="AgregarUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="activo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="rol" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObtenerCompanias" Method="ObtenerCompanias">
    <ElementType Name="ObtenerCompaniasResult">
      <Column Name="IdCompania" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ObtenerTarifas" Method="ObtenerTarifas">
    <ElementType Name="ObtenerTarifasResult">
      <Column Name="IdTarifa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>